name: Запуск автотестов

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: выберите тесты для запуска
        required: true
        type: choice
        default: all
        options:
          - smoke
          - regression
          - all

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Тесты
    steps:
      - name: Получение исходного репозитория
        uses: actions/checkout@v4
      - name: Настройка среды Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"
      - name: Установка зависимостей
        run: pip install -r requirements.txt
      - name: Запуск всех тестов
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest -v --alluredir=allure-results
        continue-on-error: true
      - name: Запуск смоук-тестов
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -v -m smoke --alluredir=allure-results
        continue-on-error: true
      - name: Запуск регрессионных тестов
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -v -m regression --alluredir=allure-results
        continue-on-error: true
      - name: Установка Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Установка Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz && 
          sudo tar -zxvf allure-2.29.0.tgz -C /opt/ &&
          sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
      - name: Генерация отчета
        run: allure generate -c allure-results -o _site
      - name: Сохранение отчета как артефакта
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention-days: 1

  publish-report:
    name: Публикация отчета
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Скачивание артефактов
        uses: actions/download-artifact@v4
      - name: Загрузка артефакта страниц
        uses: actions/upload-pages-artifact@v3
      - name: Развертывание на GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
